name: Remove inactive Docker images
description: Remove Docker images inactive since at least 1 month

inputs:
  docker_org:
    description: "Docker registry (i.e. Docker Hub) organization"
    default: "jahia"
  docker_repository:
    description: "Docker registry (i.e. Docker Hub) repository"
    required: true
  docker_username:
    description: "Docker registry (i.e. Docker Hub) username"
    default: ""
    required: true
  docker_delete_token:
    description: "Docker registry (i.e. Docker Hub) token. Requires read/write/delete access"
    required: true
  dry-run:
    description: "Dry Run: Does not push changes if true"
    default: true

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_delete_token }}
    - name: Remove inactive images with DockerHub API
      shell: bash
      run: |
        TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${{ inputs.docker_username }}'", "password": "'${{ inputs.docker_delete_token }}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
        echo "Identifying and deleting images which are older than 1 months in ${{ inputs.docker_org }}/${{ inputs.docker_repository }}"
        echo
        echo "Looping through ${{ inputs.docker_repository }} repository"
        echo
        COUNT=$(curl -s -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/namespaces/${{ inputs.docker_org }}/repositories/${{ inputs.docker_repository }}/images/?status=inactive | jq '.count')
        echo "COUNT: ${COUNT}"
        PAGES=$(( ${COUNT}/100 ))
        echo "PAGES: ${PAGES}"
        for (( p=1; p<=${PAGES}; p++ )); do
          PAGE="https://hub.docker.com/v2/namespaces/${{ inputs.docker_org }}/repositories/${{ inputs.docker_repository }}/images/?page=${p}&status=inactive&page_size=100"
          echo "PAGE: ${PAGE}"
          IMAGES=$(curl -s -H "Authorization: JWT ${TOKEN}" ${PAGE} | jq '.results|.[]|.digest')
          for d in ${IMAGES}
          do
            echo
            echo "Current digest: ${d}"
            echo
            curl -s -H "Authorization: JWT ${TOKEN}" -H "Content-Type: application/json" -X POST -d '{"dry_run": ${{ inputs.dry_run }}, "manifests": [{"repository": "'${{ inputs.docker_repository }}'", "digest": '${d}'}]}' https://hub.docker.com/v2/namespaces/${{ inputs.docker_org }}/delete-images
          done
        done
