name: Get unused Java dependencies
description: Create an issue with unused and duplicated Java dependencies

inputs:
  default_issue_assignee:
    description: 'Default user to be assigned to new issues'
    required: true
  github_token:
    description: 'Github token'
    required: true
  root_folder:
    description: 'Change the root folder'
    default: "."

runs:
  using: "composite"
  steps:
    - name: Save/Restore dependencies from cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: |
          ~/.m2

    - name: Look for unused librairies
      if: always()
      shell: bash
      run: |
        mvn -f ${{ inputs.root_folder }}/pom.xml dependency:analyze-report -DignoreNonCompile=true --no-transfer-progress

    - name: Convert HTML to Markdown
      id: html2markdown
      if: always()
      uses: rknj/html2markdown@v1.1.0
      with:
        html-file: "${{ inputs.root_folder }}/target/site/dependency-analysis.html"

    - name: Clean up markdown
      if: always()
      shell: bash
      run: |
        echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        grep -Eiv "^.*Dependencies Report|.*Last Published|.*Built by Maven|.*©|.*\* \* \*" ${{ steps.html2markdown.outputs.markdown-file }} > maven-report-updated.md || true
        sed -i -r 's/### Used and Declared Dependencies/### Used and Declared Dependencies\n\<details\>\<summary\>Show the list\<\/summary>\n\<p\>/g' maven-report-updated.md
        sed -i -r 's/### Used but Undeclared Dependencies/\<\/p\>\n\<\/details\>\n\n### Used but Undeclared Dependencies\n\<details\>\<summary\>Show the list\<\/summary\>\n\<p\>/g' maven-report-updated.md
        sed -i -r 's/### Unused but Declared Dependencies/\<\/p\>\n\<\/details\>\n\n### Unused but Declared Dependencies/g' maven-report-updated.md
        echo 'MARKDOWN_UNUSED<<EOF' >> $GITHUB_ENV
        cat maven-report-updated.md >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Create an issue with the Maven report
      if: always()
      uses: dacbd/create-issue-action@v1.2.0
      with:
        token: ${{ inputs.github_token }}
        title: Maven dependency report (unused dependencies) - ${{ env.TODAY }}
        body: |
          Report from [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          Analysed folder: ${{ inputs.root_folder }}
          ${{ env.MARKDOWN_UNUSED }}
        assignees: ${{ inputs.default_issue_assignee }}

    - name: Look for duplicates (logs only)
      if: always()
      shell: bash
      run: |
        mvn -f ${{ inputs.root_folder }}/pom.xml dependency:analyze-duplicate --no-transfer-progress
