name: Chachalog / Prepare Next Release
description: Create a PR with the upcoming changelog

inputs:
  github_token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
    - run: npx chachalog@^0.4.4 prepare-next-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
