name: publish NPM

inputs:
  nexus_username:
    description: 'Nexus Username'
    required: true
  nexus_password:
    description: 'Nexus password'
    required: true
  module_path:
    description: 'Path to module'
    default: './'

runs:
  using: "composite"
  steps:

    - name: Set environment variables from parameters
      shell: bash
      run: |
        echo "NEXUS_USERNAME=${{ inputs.nexus_username }}" >> $GITHUB_ENV
        echo "NEXUS_PASSWORD=${{ inputs.nexus_password }}" >> $GITHUB_ENV
        echo "MODULE_NAME=$(jq '.name' package.json | cut -d\" -f2)" >> $GITHUB_ENV
        echo "MODULE_VERSION=$(jq '.version' package.json | cut -d\" -f2)" >> $GITHUB_ENV
        echo "REPOSITORY_ID=$(jq '.jahia.distributionManagement.snapshotRepository.id | cut -d\" -f2)" >> $GITHUB_ENV
        echo "REPOSITORY_URL=$(jq '.jahia.distributionManagement.snapshotRepository.url | cut -d\" -f2)" >> $GITHUB_ENV

    # This step save the maven cache between runs
    # More details can be found here: https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Prepare the module
      shell: bash
      run: yarn

    - name: Build the module
      shell: bash
      run: yarn build

    - name: Package the module
      shell: bash
      run: yarn pack

    - name: Publish to maven
      shell: bash
      run: mvn deploy:deploy-file -Dfile=${{ inputs.module_path }}${{ env.MODULE_NAME }}.tgz -DgroupId=org.jahia -DartifactId=${{ env.MODULE_NAME }} -Dversion=${{ env.MODULE_VERSION }} -Dpackaging=tgz -Durl=${{ env.REPOSITORY_URL }} -DrepositoryId=${{ env.REPOSITORY_ID }} 