name: Chachalog / Comment PR
description: Prompt the developer to prepare a changelog entry in the PR

inputs:
  github_token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
    - run: npx chachalog@^0.4.4 comment-pr
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
