name: Check Changelog
description: Checks changelog has been updated

inputs:
  changelog-directory:
    description: The path to the changelog directory
    default: '.chachalog'
  no-changelog-label:
    description: The name of the "no-changelog" label, indicating that a changelog is not expected in this PR
    default: '🗒️ no-changelog'

runs:
  using: composite
  steps:
    - name: Check if no-changelog label is present
      uses: actions/github-script@v8
      id: check-no-changelog
      with:
        script: |
          const labels = context.payload.pull_request.labels.map(label => label.name);
          return labels.includes("${{ inputs.no-changelog-label }}");

    - name: Is repo whitelisted?
      id: wl
      if: steps.check-no-changelog.outputs.result == 'false'
      uses: jahia/jahia-modules-action/chachalog-is-whitelisted@v2
      with:
        repository: ${{ github.repository }}

    - name: Check if changelog has been updated in the PR
      if: steps.check-no-changelog.outputs.result == 'false' && steps.wl.outputs.whitelisted == 'false'
      uses: actions/github-script@v8
      id: check-changelog-updated
      with:
        script: |
          const changelogDir = '${{ inputs.changelog-directory }}';
          const prNumber = context.payload.pull_request.number;
          const filesChanged = await github.paginate(github.rest.pulls.listFiles, {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
          });

          for (const file of filesChanged) {
            if (file.filename.startsWith(changelogDir + '/')) {
              return true;
            }
          }
          return false;

    - name: Fail if checks failed
      if: steps.check-no-changelog.outputs.result == 'false' && steps.check-repo-whitelist.outputs.result == 'false' && steps.check-changelog-updated.outputs.result == 'false'
      uses: actions/github-script@v7
      with:
        script: |
          const message = "Changelog has not been updated. Please update the changelog or add the '🗒️ no-changelog' label to skip this check.";
          core.setFailed(message);
