name: Release Rollback
description: Rollback a release by using backup files perviously cached

inputs:
  mvn_settings_filepath:
    description: Filepath to the settings.xml file
    default: '.github/maven.settings.xml'
    required: false
  release_id:
    description: GitHub release ID
    required: true
  release_version:
    description: Version to release
    required: true
  git_user_name:
    description: Git user name
    default: 'Jahia CI'
    required: false
  git_user_email:
    description: Git user email
    default: 'jahia-ci@jahia.com'
    required: false

runs:
  using: "composite"
  steps:
    - name: Deprecated action
      shell: bash
      run: echo "This action should no be used anymore, please remove any usage of it."
    - name: Create annotation
      shell: bash
      run: echo "::notice file=on-rollback.yml,title=Rollback action::This action should no be used anymore, please remove any usage of it"
