name: Release Rollback
description: Rollback a release by using backup files perviously cached

inputs:
  mvn_settings_filepath:
    description: Filepath to the settings.xml file
    default: '.circleci/.circleci.settings.xml'
    required: false
  release_id:
    description: GitHub release ID
    required: true
  release_version:
    description: Version to release
    required: true
  git_user_name:
    description: Git user name
    default: 'Jahia CI'
    required: false
  git_user_email:
    description: Git user email
    default: 'jahia-ci@jahia.com'
    required: false

runs:
  using: "composite"
  steps:
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: |
          pom.xml.releaseBackup
          release.properties
        key: v1-rollback-${{ inputs.release_id }}

    - name: Configure git
      shell: bash
      run: |
        git config user.email ${{ inputs.git_user_email }}
        git config user.name ${{ inputs.git_user_name }}

    - name: Perform release
      shell: bash
      run: |
        if [ -f pom.xml.releaseBackup ] && [ -f release.properties ]; then
          mvn -s ${{ inputs.mvn_settings_filepath }} release:rollback
        else
          echo "Error: rollback artifacts don't exist"
          exit 1
        fi

    - name: Delete github tag ${{ inputs.release_version }}
      shell: bash
      run: |
        git tag --delete ${{ inputs.release_version }}
        git push --delete origin ${{ inputs.release_version }}

