name: slack-jahia

inputs:
  job-event:
    default: "pass"
    description: "Status of the execution"
  skip-docker:
    type: boolean
    default: false
    description: "Do not show the docker command"
  docker-repo:
    default: "jahia-ee"
    description: "Docker repository"
  docker-image-tag:
    default: "8"
    description: "Docker tag"
  slack-webhook:
    description: "Webhook that allows to send on Jahia slack"
    required: true

runs:
  using: "composite"
  steps:
    - name: Empty the Docker command variable
      shell: bash
      if: ${{ inputs.skip-docker == true }}
      run: echo 'DOCKER_COMMAND=""' >> $GITHUB_ENV
    - name: Set the docker command variable
      shell: bash
      if: ${{ inputs.skip-docker == false }}
      run: echo 'DOCKER_COMMAND="\`\`\`docker pull jahia/${{ inputs.docker-repo }}:${{ inputs.docker-image-tag }}\`\`\`"' >> $GITHUB_ENV
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.4

    # if there was no failure
    - uses: slackapi/slack-github-action@v1.18.0
      if: ${{ inputs.job-event == 'pass' }}
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text":
                  {
                    "type": "mrkdwn",
                    "text": ":white_check_mark: New build available for *${{ github.event.repository.name }}* (Job artifacts: <https://github.com/Jahia/${{ github.event.repository.name }}/actions/runs/${{ github.run_number }}#artifacts|*${{ github.job_id }}*>, Branch: *${{ steps.branch-name.outputs.current_branch }}*) ${{ env.DOCKER_COMMAND }}"
                  }
              }
            ]
          } 
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - uses: slackapi/slack-github-action@v1.18.0
      if: ${{ inputs.job-event == 'fail' }}
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text":
                  {
                    "type": "mrkdwn",
                    "text": ":x: Build failure for *${{ github.event.repository.name }}* (Job artifacts: <${{ github.server_url }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}|*${{ github.job_id }}*>, Branch: *${{ steps.branch-name.outputs.current_branch }}*)"
                  }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

