name: Keep issue open
description: If an issue in closed but not in the Done column of the project, re-open the issue with a comment

inputs:
  project_prefix:
    description: Prefix of projects to consider
    required: true
  github_token:
    description: 'GitHub personal API token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Re-open an issue if not in the right column
      uses: actions/github-script@v7
      env:
        projectPrefix: ${{ inputs.project_prefix }}
      with:
        github-token: ${{ inputs.github_token }}
        result-encoding: string
        retries: 3
        script: |
          console.log("hello")

