name: Generate Changelog
description: Generate a changelog using auto

inputs:
  github_api_token:
    description: GitHub API token
    required: true
  primary_release_branch:
    description: Name of the primary release branch (master, main, ...)
    default: 'main'
    required: false
  git_user_name:
    description: Git user name
    default: 'Jahia CI'
    required: false
  git_user_email:
    description: Git user email
    default: 'jahia-ci@jahia.com'
    required: false
  node_version:
    description: 'Version of node to install on the host'
    required: false
    default: 'lts/*'
  github_artifact_retention:
    description: 'Time during which artifact are kept in Github infrastructure'
    required: false
    default: '2'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}

    - name: Setting up github configuration
      shell: bash
      run: |
        git config user.email ${{ inputs.git_user_email }}
        git config user.name ${{ inputs.git_user_name }}
        git fetch --all --tags
        git checkout ${{ inputs.primary_release_branch }}
      # mkdir -p ~/.ssh
      # ssh-keyscan github.com >> ~/.ssh/known_hosts
      # git config --global http.sslVerify false

    # - name: Getting latest changes from the remote branch
    #   shell: bash
    #   run: |
    #     echo "List all available tags"
    #     git tag
    #     echo "List all branches"
    #     git branch --all

    # See https://intuit.github.io/auto/docs/generated/changelog
    # Generate changelog by comparing the latest tag with HEAD
    - name: Update Changelog
      shell: bash
      run: |
        npm install -g auto
        GH_TOKEN=${{ inputs.github_api_token }} auto changelog
        git push --set-upstream origin HEAD:${{ inputs.primary_release_branch }}

    - name: Persist the changelog generated for the release
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: CHANGELOG.md
        path: CHANGELOG.md
        retention-days: ${{ inputs.github_artifact_retention }}
