name: Sonar Analysis
description: Analyze the code with SonarQube

inputs:
  primary_release_branch:
    description: Name of the primary release branch (master, main, ...)
    required: false
    default: main
  github_slug:
    description: 'GitHub SLUG of the module (for example: jahia/sandbox)'
    required: true
  sonar_url:
    description: 'URL to the SONAR server'
    required: true
  sonar_token:
    description: 'Authentication token for the SONAR server'
    required: true
  github_pr_id:
    description: 'ID of the pull request (for example: 5)'
    required: false
    default: ''
  mvn_settings_filepath:
    description: Filepath to the settings.xml file
    required: false
    default: '.github/maven.settings.xml'
  nexus_username:
    description: 'Nexus Username'
    required: false
    default: ''
  nexus_password:
    description: 'Nexus Password'
    required: false
    default: ''
  build_artifacts:
    description: 'Name of the artifact target folder that was saved from build stage (using upload-artifact)'
    required: false
    default: 'build-artifacts'

runs:
  using: 'composite'
  steps:
    - name: Set environment variables from parameters
      shell: bash
      run: |
        echo "NEXUS_USERNAME=${{ inputs.nexus_username }}" >> $GITHUB_ENV
        echo "NEXUS_PASSWORD=${{ inputs.nexus_password }}" >> $GITHUB_ENV

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      if: ${{ inputs.build_artifacts != '' }}
      with:
        name: ${{ inputs.build_artifacts }}

    - name: Generate Cache Key Seeds
      shell: bash
      run: |
        find . -name 'pom.xml' | sort | xargs cat > maven_cache_seed
        if [[ ! -z "${{ inputs.github_pr_id }}" ]]; then
          echo "true" > is_pr
        else
          echo "false" > is_pr
        fi

    - name: Set environment variables from parameters
      shell: bash
      run: |
        echo "SONAR_URL=${{ inputs.sonar_url }}" >> $GITHUB_ENV
        echo "SONAR_TOKEN=${{ inputs.sonar_token }}" >> $GITHUB_ENV

    - name: Displaying important variables
      shell: bash
      run: |
        echo "github_pr_id = ${{ inputs.github_pr_id }}"

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.owasp/dependency-check-data
          ~/.sonar/cache
        key: v2-sonar-owasp-dependencies-{{ checksum "is_pr" }}
        restore-keys: |
          v2-sonar-owasp-dependencies-{{ checksum "is_pr" }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Sonar Release branch analysis
      shell: bash
      run: |
        echo "Pull request number: ${{ inputs.github_pr_id }}"
        if [[ ! -z "${{ inputs.github_pr_id }}" ]]; then
          echo "Executing a PR based analysis"
          mvn -B -s ${{ inputs.mvn_settings_filepath }} sonar:sonar \
              -Dsonar.pullrequest.branch=$GITHUB_REF \
              -Dsonar.pullrequest.key=${{ inputs.github_pr_id }} \
              -Dsonar.pullrequest.base=${{ inputs.primary_release_branch }} \
              -Dsonar.pullrequest.github.repository=${{ inputs.github_slug }}
        elif [[ ${{ steps.extract_branch.outputs.branch }} == ${{ inputs.primary_release_branch }} ]]; then
          echo "Executing an analysis on the main branch"
          mvn -B -s ${{ inputs.mvn_settings_filepath }} org.owasp:dependency-check-maven:6.1.6:aggregate sonar:sonar \
            -DfailOnError=false -DskipProvidedScope=true -DskipTestScope=false -DskipSystemScope=true -Dformats=HTML,JSON \
            -Dsonar.dependencyCheck.jsonReportPath=target/dependency-check-report.json \
            -Dsonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html \
            -DretireJsAnalyzerEnabled=false -DnodeAnalyzerEnabled=false -DdataDirectory=~/.owasp/dependency-check-data
        else
          echo "Executing an analysis on branch: $GITHUB_REF"
          mvn -B -s ${{ inputs.mvn_settings_filepath }} org.owasp:dependency-check-maven:6.1.6:aggregate sonar:sonar \
              -Dsonar.branch.name=$GITHUB_REF \
              -DfailOnError=false -DskipProvidedScope=true -DskipTestScope=false -DskipSystemScope=true -Dformats=HTML,JSON \
              -Dsonar.dependencyCheck.jsonReportPath=target/dependency-check-report.json \
              -Dsonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html \
              -DretireJsAnalyzerEnabled=false -DnodeAnalyzerEnabled=false -DdataDirectory=~/.owasp/dependency-check-data
        fi
