name: Maven Cache Warmup
description: Retrieve the .m2 cache from the cache Docker container

inputs:
  docker-image:
    description: The docker image (such as jahia/cimg-mvn-cache:ga_cimg_openjdk_11.0.20-node)
    required: true
    default: 'jahia/cimg-mvn-cache:ga_cimg_openjdk_11.0.20-node'
  docker-username:
    description: 'Docker login username'
    required: true
  docker-password:
    description: 'Docker login password'
    required: true    
  m2-path: 
    description: Path on the local instance for the .m2 folder
    required: false  
    default: ''
  java-version:
    description: Version of Java to install in the environment
    required: false
    default: '11'
  java-distribution:
    description: Distribution Java to install in the environment
    required: false  
    default: 'temurin'

runs:
  using: "composite"
  steps:
    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ input.java-distribution }}
        java-version: ${{ input.java-version }}

    - name: Set Maven repository path
      shell: bash
      run: |
        if [ -z "${{ inputs.maven_repo_path }}" ]; then
          echo "MAVEN_REPO_PATH=$HOME/.m2" >> $GITHUB_ENV
          echo "Using default Maven repository path: $HOME/.m2"
        else
          echo "MAVEN_REPO_PATH=${{ inputs.m2-path }}" >> $GITHUB_ENV
          echo "Using custom Maven repository path: ${{ inputs.m2-path }}"
        fi

    - name: Docker login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Pull Docker image with Maven cache
      shell: bash
      run: docker pull ${{ inputs.docker-image }}
    
    - name: Create container from image
      shell: bash
      run: docker create --name maven-cache-container ${{ inputs.docker-image }}
    
    - name: Create local Maven directory if it doesn't exist
      shell: bash
      run: mkdir -p ${{ env.MAVEN_REPO_PATH }}/

    - name: Display Maven cache info
      shell: bash
      run: |
        echo "Maven cache size:"
        du -h -d 1 ${{ env.MAVEN_REPO_PATH }}
        echo "Number of files in Maven cache:"
        find ${{ env.MAVEN_REPO_PATH }} -type f | wc -l

    - name: Copy Maven cache from container
      shell: bash
      run: |
        # Create a temporary directory for the container's .m2 folder
        mkdir -p /tmp/container-m2
        
        # Copy .m2 directory from container to temp directory
        docker cp maven-cache-container:/root/.m2/. /tmp/container-m2/
        
        # Merge the container's .m2 content with the runner's .m2
        # Using cp with the -n flag to avoid overwriting existing files
        cp -rn /tmp/container-m2/. ${{ env.MAVEN_REPO_PATH }}
    
    - name: Clean up container
      shell: bash
      run: docker rm maven-cache-container

    - name: Display Maven cache info
      shell: bash
      run: |
        echo "Maven cache size:"
        du -h -d 1 ${{ env.MAVEN_REPO_PATH }}
        echo "Number of files in Maven cache:"
        find ${{ env.MAVEN_REPO_PATH }} -type f | wc -l
