name: Post Documentation Guidelines Comment
description: Posts a comment on PRs that modify documentation files with links to writing guidelines

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  docs-folder:
    description: 'Folder path to monitor for documentation changes (e.g., docs/)'
    default: 'docs/'
    required: false

runs:
  using: "composite"
  steps:
    - name: Check for docs changes and post comment
      uses: actions/github-script@v7
      env:
        DOCS_FOLDER: ${{ inputs.docs-folder }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const docsFolder = process.env.DOCS_FOLDER;
          
          // Get the list of files changed in the PR
          const { data: files } = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          });
          
          // Check if any file in the PR touches the docs folder
          const hasDocsChanges = files.some(file => file.filename.startsWith(docsFolder));
          
          if (!hasDocsChanges) {
            core.info(`No changes detected in ${docsFolder} folder. Skipping comment.`);
            return;
          }
          
          core.info(`Changes detected in ${docsFolder} folder. Checking for existing comment...`);
          
          // Check if we already posted a comment with this header
          const commentHeader = 'docs-guidelines-comment';
          const comments = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const existingComment = comments.data.find(comment => 
            comment.body && comment.body.includes(`<!-- ${commentHeader} -->`)
          );
          
          if (existingComment) {
            core.info('Comment already exists. Skipping duplicate comment.');
            return;
          }
          
          // Post the comment
          const commentBody = `<!-- ${commentHeader} -->
          ## 📝 Documentation Guidelines
          
          Thank you for contributing to our documentation! To ensure your contributions meet our standards, please review these resources:
          
          - **[How to push markdown documents to the Academy](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/634159106/Documentation+in+the+codebases)** - Learn the process for publishing documentation
          - **[Documentation style guide and writing guidelines](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2065360/Documentation+style+guide)** - Follow our style conventions
          
          _This comment is posted automatically when changes are detected in the \`${docsFolder}\` folder._`;
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: commentBody,
          });
          
          core.info('Documentation guidelines comment posted successfully!');
