name: Publish
description: Publish a Jahia module to NEXUS

inputs:
  mvn_settings_filepath:
    description: Filepath to the settings.xml file
    default: '.circleci/.circleci.settings.xml'
    required: false
  nexus_username:
    description: 'Nexus Username'
    required: true
  nexus_password:
    description: 'Nexus Password'
    required: true
  nexus_internal_url:
    description: 'Nexus Internal URL'
    required: false
    default: '${{ secrets.NEXUS_INTERNAL_URL }}'

runs:
  using: "composite"
  steps:
    - name: Set environment variables from parameters
      shell: bash
      run: |
        echo "NEXUS_USERNAME=${{ inputs.nexus_username }}" >> $GITHUB_ENV
        echo "NEXUS_PASSWORD=${{ inputs.nexus_password }}" >> $GITHUB_ENV
        echo "NEXUS_INTERNAL_URL=${{ inputs.nexus_internal_url }}" >> $GITHUB_ENV

    # This step save the maven cache between runs
    # More details can be found here: https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build package
      shell: bash
      run: mvn -B -s ${{ inputs.mvn_settings_filepath }} clean deploy
