name: "Delivery - Lint PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  prs-chores:
    uses:  Jahia/jahia-modules-action/.github/workflows/prs-chores.yml@2281-create-a-pr-chores-workflow
    secrets: inherit
