name: "Delivery - PR Chores"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  rf:
    uses:  Jahia/jahia-modules-action/.github/workflows/prs-chores.yml@2281-create-a-pr-chores-workflow
    secrets: inherit
