# This workflow performs various tasks for cleanup, triage, ... on an individual GitHub Issue
# It should be called based on issue events
name: Issue Chores

on:
  workflow_call:

jobs:
  general:
    name: General Issue operations
    runs-on: ubuntu-latest
    steps:
      # Provides additional data if it becomes needed to debug a particular event
      - name: Displays details about the event
        uses: actions/github-script@v7
        with:
          script: |
            core.info(`context.eventName: ${context.eventName}`)
            core.info(`context.payload.action: ${context.payload.action}`)
            core.info(`context.payload.issue.node_id: ${context.payload.issue.node_id}`)
            core.info(`context.payload.issue.number: ${context.payload.issue.number}`)
            core.info(`context.payload.issue.html_url: ${context.payload.issue.html_url}`)
            core.info(`context.payload.sender.login: ${context.payload.sender.login}`)
            core.debug(context)

      - name: Re-open an issue if it is closed but not in the Done column
        uses: jahia/jahia-modules-action/delivery/keep-issue-open@v2
        with:
          github_token: ${{ secrets.GH_ISSUES_PRS_CHORES }}
          project_prefix: "Team - "

  projects-label:
    name: Projects on Labels
    if: ${{ github.event.action == 'labeled' }}
    runs-on: ubuntu-latest
    steps:
      # Issue type is not available by default, this makes it available for if conditions
      - name: Get Issue type
        uses: actions/github-script@v7
        id: get-issue-type
        with:
          script: if (context.payload.issue.type !== undefined) {return context.payload.issue.type.name}
          result-encoding: string

      # Using an official action from GitHub to attach issues to projects
      # https://github.com/marketplace/actions/add-to-github-projects
      - name: Attach needs-triage to the Bugs Triage project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Jahia/projects/13
          github-token: ${{ secrets.GH_ISSUES_PRS_CHORES }}
          labeled: need-triage

      - name: Attach customers to the Customers project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Jahia/projects/24
          github-token: ${{ secrets.GH_ISSUES_PRS_CHORES }}
          labeled: customer

      # Add all tickets of Type "Epic" and label "Area:" to the global roadmap project
      - name: Attach all Epics to the Roadmap - Global project
        uses: actions/add-to-project@v1.0.2
        if: ${{ steps.get-issue-type.outputs.result == 'Epic'}}
        with:
          project-url: https://github.com/orgs/Jahia/projects/18
          github-token: ${{ secrets.GH_ISSUES_PRS_CHORES }}
          labeled: Area:Product, Area:Delivery, Area:Tech, Area:QA, Area:Security
          label-operator: OR

      - name: Attach all tickets with label Area:QA to the QA Roadmap Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Jahia/projects/21
          github-token: ${{ secrets.GH_ISSUES_PRS_CHORES }}
          labeled: Area:QA

      - name: Attach all tickets with label Area:Tech to the Tech Roadmap Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Jahia/projects/23
          github-token: ${{ secrets.GH_ISSUES_PRS_CHORES }}
          labeled: Area:Tech

      - name: Attach all tickets with label Area:Delivery to the Delivery Roadmap Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Jahia/projects/12
          github-token: ${{ secrets.GH_ISSUES_PRS_CHORES }}
          labeled: Area:Delivery

      - name: Attach all tickets with label Area:Security and incident to the Security Roadmap Project
        uses: actions/add-to-project@v1.0.2
        id: new-security-incident
        with:
          project-url: https://github.com/orgs/Jahia/projects/22
          github-token: ${{ secrets.GH_ISSUES_PRS_CHORES }}
          labeled: Area:Security, incident
          label-operator: AND

      - name: Create a Security Jira ticket
        uses: jahia/jahia-modules-action/delivery/create-security-ticket@v2
        if: ${{ steps.new-security-incident.outputs.itemId != '' }}
        with:
          jira-host: 'jira.jahia.org'
          jira-project: 'SECBACKLOG'
          jira-username: ${{ secrets.JIRA_USERNAME }}
          jira-password: ${{ secrets.JIRA_PASSWORD }}
          github-token: ${{ secrets.GH_ISSUES_PRS_CHORES }}
          github-security-project: 'Area - Security'
          github-field: 'Jira tickets'

      - name: Attach all tickets with label Area:QA to the Security Roadmap Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Jahia/projects/22
          github-token: ${{ secrets.GH_ISSUES_PRS_CHORES }}
          labeled: Area:Security

      # The refresh label is useful to trigger this workflow
      # It gets automatically removed
      - name: Remove the refresh label
        uses: mondeja/remove-labels-gh-action@v2
        with:
          token: ${{ secrets.GH_ISSUES_PRS_CHORES }}
          labels: refresh

  projects-milestone:
    name: Projects on Milestones
    if: ${{ github.event.action == 'milestoned' || github.event.action == 'demilestoned' }}
    runs-on: ubuntu-latest
    steps:
      # Adds or removes the "Product Releases" project if a milestone is added
      # or removed
      - name: Attach Project based on the presence of a milestone
        uses: jahia/jahia-modules-action/delivery/add-project-based-on-milestone@v2
        with:
          project_url: https://github.com/orgs/Jahia/projects/29
          github_token: ${{ secrets.GH_ISSUES_PRS_CHORES }}

  transfer:
    name: Transfer
    runs-on: ubuntu-latest
    needs: [projects-label, projects-milestone]
    if: always()
    steps:
      # Transfer issues with label "jahia-only" back to jahia-private
      - name: Transfer Issue & Create Stub
        uses: lando/transfer-issue-action@v2
        with:
          token: ${{ secrets.GH_JAHIACI_ISSUES_CHORES }}        
          router: jahia-only:jahia-private      
      - name: Update Transferred Issue
        uses: actions/github-script@v7
        if: steps.transfer-issue.outputs.new_issue_number != ''
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: `${{ steps.transfer-issue.outputs.new_issue_number}}`,
              owner: context.repo.owner,
              repo: `${{ steps.transfer-issue.outputs.destinatiom_repo }}`,
              body: `@${ context.payload.issue.user.login } your issues was moved back to jahia/jahia-private since it contained the jahia-only label!`
            });

      # If labeled with delete, the issue is transffered to a dedicated repository
      - name: Transfer Issue for deletion
        uses: lando/transfer-issue-action@v2
        with:
          token: ${{ secrets.GH_JAHIACI_ISSUES_CHORES }}        
          router: delete:deleted-issues     

      # Transfer issues between repositories of the Jahia org
      - name: Transfer Issue & Create Stub
        uses: Fgerthoffert/actions-transfer-issue@v1.0.0
        if: ${{ github.event.action == 'labeled' }}
        with:
          token: ${{ secrets.GH_ISSUES_PRS_CHORES }}        
          router: "transfer:"
          allow_private_public_transfer: true

  links:
    name: Links
    runs-on: ubuntu-latest
    needs: transfer
    if: always()
    steps:
      # If the issue was moved to a different repository it will not be possible to attach links
      # In that case skip the link creation, which will be handled next time an event happens on the issue
      - name: Check if the issue still exists in the repository
        uses: jahia/jahia-modules-action/delivery/check-issue-exists@v2
        id: issue-exists
        with:
          github_token: ${{ secrets.GH_ISSUES_PRS_CHORES }}

      # Create links in Jira to GitHub Issues
      # We still need to create a Jira User and update the server_host
      - name: Create links to GitHub in Jira issues
        uses: Fgerthoffert/actions-create-jira-link@v1.1.0
        if: steps.transfer-issue.outputs.new_issue_number != ''
        with:
          token: ${{ secrets.GH_ISSUES_PRS_CHORES }}
          jira_server_host: jira.jahia.org
          jira_server_username: ${{ secrets.JIRA_USERNAME }}
          jira_server_password: ${{ secrets.JIRA_PASSWORD }}
          github_project_field: "Jira tickets"
          github_fail_issue_not_found: false
