# This workflow performs various tasks for cleanup, triage, ... on GitHub Issues
name: Issues Chores

on:
  workflow_call:
    inputs:
      instance_type:
        type: string
        required: false
        description: "Type of instances to run the job on (self hosted or ubuntu-latest)"
        default: "self-hosted"

jobs:
  issues-chores:
    name: Issues Chores
    runs-on: ubuntu-latest
    steps:
      # Issue type is not available by default, this makes it available for if conditions
      - name: Get Issue type
        uses: actions/github-script@v7
        id: get-issue-type
        with:
          script: if (context.payload.issue.type !== undefined) {return context.payload.issue.type.name}
          result-encoding: string

      # https://github.com/marketplace/actions/add-to-github-projects
      # Add all issues with need-triage label to the "Bug Triage" project
      # Official Action from GitHub
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Jahia/projects/13
          github-token: ${{ secrets.GH_JAHIACI_ISSUES_CHORES }}
          labeled: needs-triage

      # Transfer issues with label "jahia-only" back to jahia-private
      - name: Transfer Issue & Create Stub
        uses: lando/transfer-issue-action@v2
        with:
          token: ${{ secrets.GH_JAHIACI_ISSUES_CHORES }}        
          router: jahia-only:jahia-private      
      - name: Update Transferred Issue
        uses: actions/github-script@v5
        if: steps.transfer-issue.outputs.new_issue_number != ''
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: `${{ steps.transfer-issue.outputs.new_issue_number}}`,
              owner: context.repo.owner,
              repo: `${{ steps.transfer-issue.outputs.destinatiom_repo }}`,
              body: `@${ context.payload.issue.user.login } your issues was moved back to jahia/jahia-private since it contained the jahia-only label!`
            });

      #
      # Attach issues to projects
      #
      # Add all tickets of Type "Epic" and label "Area:" to the global roadmap project
      # https://github.com/orgs/Jahia/projects/18
      - name: Attach all Epics to the Roadmap - Global project
        uses: actions/add-to-project@v1.0.2
        if: ${{ steps.get-issue-type.outputs.result == 'Epic' }}
        with:
          project-url: https://github.com/orgs/Jahia/projects/18
          github-token: ${{ secrets.GH_JAHIACI_ISSUES_CHORES }}
          labeled: Area:Product, Area:Delivery, Area:Tech, Area:QA, Area:Security
          label-operator: OR

      # https://github.com/orgs/Jahia/projects/21
      - name: Attach all tickets with label Area:QA to the QA Roadmap Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Jahia/projects/21
          github-token: ${{ secrets.GH_JAHIACI_ISSUES_CHORES }}
          labeled: Area:QA

      # https://github.com/orgs/Jahia/projects/22
      - name: Attach all tickets with label Area:QA to the Security Roadmap Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Jahia/projects/22
          github-token: ${{ secrets.GH_JAHIACI_ISSUES_CHORES }}
          labeled: Area:Security

      # https://github.com/orgs/Jahia/projects/23
      - name: Attach all tickets with label Area:Tech to the Tech Roadmap Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Jahia/projects/22
          github-token: ${{ secrets.GH_JAHIACI_ISSUES_CHORES }}
          labeled: Area:Tech

      # https://github.com/orgs/Jahia/projects/23
      - name: Attach all tickets with label Area:Delivery to the Delivery Roadmap Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Jahia/projects/22
          github-token: ${{ secrets.GH_JAHIACI_ISSUES_CHORES }}
          labeled: Area:Delivery