name: Release Module

on:
  workflow_call:
    inputs:
      instance_type:
        type: string
        required: false
        description: "Type of instances to run the job on (self hosted or ubuntu-latest)"
        default: "ubuntu-latest"    
      mvn_settings_filepath:
        type: string
        description: Filepath to the settings.xml file
        default: ".github/maven.settings.xml"
        required: false
      job_container:
        type: string
        required: false
        default: "jahia/cimg-mvn-cache:ga_cimg_openjdk_11.0.20-node"
      primary_release_branch:
        type: string
        required: false
        default: "main"
      github_slug:
        type: string
        required: false
        default: ""
      nexus_username:
        type: string
        required: false
        default: ""        
      nexus_password:
        type: string
        required: false
        default: "" 
      tests_module_path:
        type: string
        description: "Path to a folder in the repository containing a tests module to be built (Both NPM and MVN test module supported)"
        required: false
        default: "tests/jahia-module/"
      tests_module_type:
        type: string
        description: "Type of module for the tests module (mvn,npm)"
        required: false
        default: "mvn"          
      git_user_name:
        type: string
        description: Git user name
        default: "Jahia CI"
        required: false
      git_user_email:
        type: string
        description: Git user email
        default: "jahia-ci@jahia.com"
        required: false
      github_artifact_retention:
        type: string
        description: "Time during which artifact are kept in Github infrastructure"
        required: false
        default: "2"

jobs:
  release-module:
    name: Release Module
    runs-on: ${{ inputs.instance_type }}
    container:
      image: ${{ inputs.job_container }}
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Add safe directory
        shell: bash
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      # Providing the SSH PRIVATE of a user part of an admin group
      # is necessary to bypass PR checks
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY_JAHIACI }}

      # Setting up the SSH agent to be able to commit back to the repository
      # https://github.com/webfactory/ssh-agent
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GH_SSH_PRIVATE_KEY_JAHIACI }}

      - name: Configure github_slug
        shell: bash
        run: |
          echo "GITHUB_SLUG=${{ inputs.github_slug }}" >> $GITHUB_ENV
          if [[ "${{ inputs.github_slug }}" == "" ]]; then
            echo "GITHUB_SLUG=${{ github.repository }}" >> $GITHUB_ENV
          fi
          echo "GITHUB_SLUG=${{ inputs.github_slug }}" >> $GITHUB_ENV

      - name: Prepare Nexus credentials
        shell: bash
        run: |
          echo "NEXUS_USERNAME=${{ inputs.nexus_username }}" >> $GITHUB_ENV
          if [[ "${{ inputs.nexus_username }}" == "" ]]; then
            echo "NEXUS_USERNAME=${{ secrets.NEXUS_USERNAME }}" >> $GITHUB_ENV
          fi
          echo "NEXUS_PASSWORD=${{ inputs.nexus_password }}" >> $GITHUB_ENV
          if [[ "${{ inputs.nexus_password }}" == "" ]]; then
            echo "NEXUS_PASSWORD=${{ secrets.NEXUS_PASSWORD }}" >> $GITHUB_ENV
          fi

      - uses: jahia/jahia-modules-action/release@v2
        name: Release Module
        with:
          primary_release_branch: ${{ inputs.primary_release_branch }}
          mvn_settings_filepath: ${{ inputs.mvn_settings_filepath }}
          nexus_username: ${{ env.NEXUS_USERNAME }}
          nexus_password: ${{ env.NEXUS_PASSWORD }}
          tests_module_path: ${{ inputs.tests_module_path }}
          tests_module_type: ${{ inputs.tests_module_type }}
          github_slug: ${{ env.GITHUB_SLUG }}          
          release_id: ${{ github.event.release.id }}
          release_version: ${{ github.event.release.tag_name }}
          git_user_name: ${{ inputs.git_user_name }}
          git_user_email: ${{ inputs.git_user_email }}
          github_api_token: ${{ secrets.GH_API_TOKEN }}
          github_artifact_retention: ${{ inputs.github_artifact_retention }}
          slack-webhook-qa: ${{ secrets.SLACK_WEBHOOK_URL_RC_FOR_QA }}

      - uses: jahia/jahia-modules-action/update-signature@v2
        with:
          nexus_username: ${{ inputs.nexus_username }}
          nexus_password: ${{ inputs.nexus_password }}
          nexus_enterprise_releases_url: ${{ secrets.NEXUS_ENTERPRISE_RELEASES_URL }}
          force_signature: true

  sbom:
    name: SBOM processing
    needs: release-module
    runs-on: ubuntu-latest
    container:
      image: cyclonedx/cyclonedx-cli:0.24.2   
    steps:
      - uses: jahia/jahia-modules-action/sbom-processing@v2
        with:
          dependencytrack_hostname: ${{ vars.DEPENDENCYTRACK_HOSTNAME }}
          dependencytrack_apikey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}